services:

  clickhouse:
    image: clickhouse/clickhouse-server:25.8
    container_name: de-clickhouse

    ports:
      - "8123:8123"
      - "9000:9000"

    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}

    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./src/sql:/app/sql:ro
      - ./docker/clickhouse/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro

    mem_limit: 3g
    restart: unless-stopped

    healthcheck:
      test:
        - CMD
        - clickhouse-client
        - --user
        - ${CLICKHOUSE_USER}
        - --password
        - ${CLICKHOUSE_PASSWORD}
        - --query
        - SELECT 1
      interval: 5s
      timeout: 5s
      retries: 10

  raw-loader:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: de-raw-loader

    environment:
      CLICKHOUSE_HOST: ${CLICKHOUSE_HOST}
      CLICKHOUSE_PORT: ${CLICKHOUSE_PORT}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DATABASE: ${CLICKHOUSE_DATABASE}

      KAFKA_HOST: ${KAFKA_HOST}
      KAFKA_PORT: ${KAFKA_PORT}
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      KAFKA_CONSUMER_GROUP: ${KAFKA_CONSUMER_GROUP}
      KAFKA_USER: ${KAFKA_USER}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}

      CERT_PATH: /app/certs/YandexInternalRootCA.crt

    volumes:
      - ${CERT_PATH}:/app/certs/YandexInternalRootCA.crt:ro

    command:
      - python
      - -m
      - raw_loader.load_kafka_events

    depends_on:
      clickhouse:
        condition: service_healthy

    restart: unless-stopped

  airflow-postgres:
    image: postgres:16
    container_name: de-airflow-postgres

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U airflow -d airflow
      interval: 5s
      timeout: 5s
      retries: 10

    restart: unless-stopped

  airflow-init:
    image: apache/airflow:2.11.2-python3.12
    container_name: de-airflow-init

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}

      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      _PIP_ADDITIONAL_REQUIREMENTS: apache-airflow-providers-clickhousedb==1.0.0

    depends_on:
      airflow-postgres:
        condition: service_healthy

    command:
      - bash
      - -c
      - |
        airflow db migrate &&
        airflow users create \
          --username admin \
          --password admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com

        airflow connections delete clickhouse_conn || true

        airflow connections add clickhouse_conn \
          --conn-type clickhouse \
          --conn-host clickhouse \
          --conn-login "${CLICKHOUSE_USER}" \
          --conn-password "${CLICKHOUSE_PASSWORD}" \
          --conn-port 8123 &&

        airflow variables set stg_batch_size 100000 &&
        airflow variables set stg_transactions_last_offset -1 &&
        airflow variables set stg_currencies_last_offset -1 &&
        airflow variables set dds_start_date 2022-10-01 &&
        airflow variables set dds_end_date 2022-11-01 &&
        airflow variables set cdm_start_date 2022-10-01 &&
        airflow variables set cdm_end_date 2022-11-01


  airflow-webserver:
    image: apache/airflow:2.11.2-python3.12
    container_name: de-airflow-webserver

    ports:
      - "8080:8080"

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      PYTHONPATH: /opt/airflow/src/py

      AIRFLOW__WEBSERVER__DEFAULT_DAG_RUN_DISPLAY_NUMBER: 31

      _PIP_ADDITIONAL_REQUIREMENTS: apache-airflow-providers-clickhousedb==1.0.0

    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - airflow_logs:/opt/airflow/logs

    depends_on:
      airflow-init:
        condition: service_completed_successfully

    command: webserver

    restart: unless-stopped

  airflow-scheduler:
    image: apache/airflow:2.11.2-python3.12
    container_name: de-airflow-scheduler

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}

      PYTHONPATH: /opt/airflow/src/py
      KAFKA_TOPIC: ${KAFKA_TOPIC}

      _PIP_ADDITIONAL_REQUIREMENTS: apache-airflow-providers-clickhousedb==1.0.0

    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - airflow_logs:/opt/airflow/logs

    depends_on:
      airflow-init:
        condition: service_completed_successfully

    command: scheduler

    restart: unless-stopped

  metabase:
    image: metabase/metabase:v0.63.15
    container_name: de-metabase

    ports:
      - "3000:3000"

    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase-data/metabase.db

    volumes:
      - metabase_data:/metabase-data

    depends_on:
      clickhouse:
        condition: service_healthy

    restart: unless-stopped

volumes:
  clickhouse_data:
  airflow_postgres_data:
  airflow_logs:
  metabase_data: