FROM apache/airflow:2.10.5-python3.12

USER root

WORKDIR /opt/airflow

COPY requirements.txt /tmp/requirements.txt
COPY src /opt/airflow/src

USER airflow

RUN pip install --no-cache-dir -r /tmp/requirements.txt

ENV PYTHONPATH=/opt/airflow/src/py